import { z } from "zod";

const decimalAmount = z
  .string()
  .trim()
  .regex(/^\d+(\.\d{1,2})?$/, "Enter an amount like 15.50");

export const completeSaleSchema = z.object({
  /**
   * Generated by the client before its first attempt and reused on every
   * retry. This is what makes a dropped connection safe: the same key returns
   * the same sale instead of selling the stock twice.
   */
  clientTransactionId: z.uuid("A transaction reference is required"),

  items: z
    .array(
      z.object({
        productId: z.uuid(),
        /**
         * Which selling unit — a Box rather than a Piece. Omitted means the
         * product's default unit, so a client that does not offer the choice
         * still sells the right thing.
         */
        productUnitId: z.uuid().optional(),
        /** Omitted means retail. Wholesale is refused when no price is set. */
        priceTier: z.enum(["retail", "wholesale"]).optional(),
        quantity: z.coerce
          .number()
          .int("Quantities are whole units")
          .min(1, "Quantity must be at least 1"),
      }),
    )
    .min(1, "Add at least one product before completing the sale"),

  /**
   * No price and no total. The server reads both from the catalogue, so
   * there is nothing here for a modified client to lie about.
   */
  payments: z
    .array(
      z.object({
        method: z.enum(["cash", "mobile_money"]),
        amount: decimalAmount,
        reference: z.string().trim().max(100).nullable().optional(),
      }),
    )
    .min(1, "Record how the sale was paid for"),
});

export type CompleteSaleInput = z.input<typeof completeSaleSchema>;

export const voidSaleSchema = z.object({
  saleId: z.uuid(),
  reason: z.string().trim().min(1, "Give a reason for voiding the sale").max(200),
});
