import type { PaymentMethod } from "../entities/payment";
import type { ProductId, SaleId, StaffId } from "../entities/identifiers";
import type { Sale } from "../entities/sale";
import type { Money } from "../value-objects/money";
import type { DateRange, Page, PageRequest } from "./shared";

/**
 * What is sold, and how many.
 *
 * No price, no line total, deliberately. The store of record prices the sale
 * itself from the catalogue; passing a price through this contract would
 * create a channel where one could be forged, and a channel that exists gets
 * used eventually.
 */
export interface RecordSaleLine {
  readonly productId: ProductId;
  readonly quantity: number;
}

export interface RecordSalePayment {
  readonly method: PaymentMethod;
  readonly amount: Money;
  readonly reference: string | null;
}

export interface RecordSaleCommand {
  readonly lines: readonly RecordSaleLine[];
  readonly payments: readonly RecordSalePayment[];
  /**
   * Idempotency key generated by the client before the first attempt. If the
   * network drops after the database committed but before the response
   * arrived, the retry carries the same key and returns the original sale
   * instead of selling the stock twice.
   */
  readonly clientTransactionId: string;
}

export interface SaleFilter {
  readonly range?: DateRange;
  readonly cashierId?: StaffId;
  readonly paymentMethod?: PaymentMethod | "split";
  readonly search?: string;
}

export interface SalesRepository {
  /**
   * Writes the whole transaction — sale, items, payments, stock decrements and
   * movement rows — in one atomic database operation.
   *
   * The implementation calls a single plpgsql function so that either all of
   * it happens or none of it does. There is no code path that can leave stock
   * reduced without a sale, or a sale recorded without reducing stock.
   */
  record(command: RecordSaleCommand): Promise<Sale>;

  findById(id: SaleId): Promise<Sale | null>;
  findByReceiptNumber(receiptNumber: string): Promise<Sale | null>;
  /** Returns the existing sale for an already-used idempotency key. */
  findByClientTransactionId(clientTransactionId: string): Promise<Sale | null>;
  list(filter: SaleFilter, page: PageRequest): Promise<Page<Sale>>;
  /**
   * Reverses a sale: restores stock, writes reversal movements, marks voided.
   * Who voided it comes from the session, like everything else that matters.
   */
  void(id: SaleId, reason: string): Promise<Sale>;
}
