/**
 * Entity identifiers are UUIDs generated by Postgres. The domain treats them
 * as opaque strings — it never generates one, never parses one, and never
 * assumes an ordering. Branded aliases keep a ProductId from being passed
 * where a StaffId belongs.
 */
declare const brand: unique symbol;

type Branded<T, B extends string> = T & { readonly [brand]: B };

export type ProductId = Branded<string, "ProductId">;
export type CategoryId = Branded<string, "CategoryId">;
export type StaffId = Branded<string, "StaffId">;
export type SaleId = Branded<string, "SaleId">;
export type SaleItemId = Branded<string, "SaleItemId">;
export type PaymentId = Branded<string, "PaymentId">;
export type ExpenseId = Branded<string, "ExpenseId">;
export type ExpenseCategoryId = Branded<string, "ExpenseCategoryId">;
export type MovementId = Branded<string, "MovementId">;

export const asProductId = (value: string) => value as ProductId;
export const asCategoryId = (value: string) => value as CategoryId;
export const asStaffId = (value: string) => value as StaffId;
export const asSaleId = (value: string) => value as SaleId;
export const asSaleItemId = (value: string) => value as SaleItemId;
export const asPaymentId = (value: string) => value as PaymentId;
export const asExpenseId = (value: string) => value as ExpenseId;
export const asExpenseCategoryId = (value: string) =>
  value as ExpenseCategoryId;
export const asMovementId = (value: string) => value as MovementId;
