import { ValidationError } from "../errors/domain-error";
import { Money } from "../value-objects/money";
import { Quantity } from "../value-objects/quantity";
import type {
  ProductId,
  SaleId,
  SaleItemId,
  StaffId,
} from "./identifiers";
import type { Payment, PaymentMethod } from "./payment";

export const SALE_STATUSES = ["completed", "voided"] as const;
export type SaleStatus = (typeof SALE_STATUSES)[number];

export interface SaleItemProps {
  readonly id: SaleItemId;
  readonly productId: ProductId;
  /**
   * SKU, name and unit price are copied onto the line, not joined at read
   * time. A receipt reprinted next year must show what was actually sold at
   * the price it was actually sold for, even if the product was since renamed,
   * repriced or deleted from the catalogue.
   */
  readonly sku: string;
  readonly name: string;
  readonly unitPrice: Money;
  readonly quantity: Quantity;
  readonly lineTotal: Money;
  /** Unit cost at the time of sale, when known. Null makes profit incalculable. */
  readonly unitCost: Money | null;
}

export class SaleItem {
  private constructor(private readonly props: SaleItemProps) {
    Object.freeze(this);
  }

  static create(props: SaleItemProps): SaleItem {
    const expected = props.unitPrice.multiply(props.quantity.toNumber());
    if (!expected.equals(props.lineTotal)) {
      throw new ValidationError(
        "Line total does not match unit price times quantity.",
        {
          expected: expected.toDecimalString(),
          actual: props.lineTotal.toDecimalString(),
        },
      );
    }
    return new SaleItem(props);
  }

  get id(): SaleItemId {
    return this.props.id;
  }
  get productId(): ProductId {
    return this.props.productId;
  }
  get sku(): string {
    return this.props.sku;
  }
  get name(): string {
    return this.props.name;
  }
  get unitPrice(): Money {
    return this.props.unitPrice;
  }
  get quantity(): Quantity {
    return this.props.quantity;
  }
  get lineTotal(): Money {
    return this.props.lineTotal;
  }
  get unitCost(): Money | null {
    return this.props.unitCost;
  }

  /** Null when cost was not recorded — never assume zero cost. */
  get lineProfit(): Money | null {
    if (!this.props.unitCost) return null;
    return this.props.lineTotal.subtract(
      this.props.unitCost.multiply(this.props.quantity.toNumber()),
    );
  }
}

export interface SaleProps {
  readonly id: SaleId;
  /** Human-facing, gap-free, generated by the database. e.g. "AMX-000142". */
  readonly receiptNumber: string;
  readonly cashierId: StaffId;
  readonly cashierName: string;
  readonly items: readonly SaleItem[];
  readonly total: Money;
  readonly payments: readonly Payment[];
  readonly status: SaleStatus;
  /**
   * Client-generated idempotency key. Two submissions carrying the same key
   * are the same sale, which is what stops a flaky connection turning one
   * transaction into two.
   */
  readonly clientTransactionId: string;
  readonly soldAt: Date;
}

/**
 * A completed transaction. Immutable once written.
 *
 * A sale is never edited — a mistake is corrected by voiding, which writes
 * reversing stock movements and leaves both records in the history.
 */
export class Sale {
  private constructor(private readonly props: SaleProps) {
    Object.freeze(this);
  }

  static create(props: SaleProps): Sale {
    if (props.items.length === 0) {
      throw new ValidationError("A sale must have at least one item.");
    }

    const itemsTotal = Money.sum(props.items.map((item) => item.lineTotal));
    if (!itemsTotal.equals(props.total)) {
      throw new ValidationError("Sale total does not match its line items.", {
        itemsTotal: itemsTotal.toDecimalString(),
        recordedTotal: props.total.toDecimalString(),
      });
    }

    if (props.status === "completed") {
      const paid = Money.sum(props.payments.map((payment) => payment.amount));
      if (!paid.equals(props.total)) {
        throw new ValidationError(
          "Recorded payments do not add up to the sale total.",
          {
            paid: paid.toDecimalString(),
            total: props.total.toDecimalString(),
          },
        );
      }
    }

    return new Sale(props);
  }

  get id(): SaleId {
    return this.props.id;
  }
  get receiptNumber(): string {
    return this.props.receiptNumber;
  }
  get cashierId(): StaffId {
    return this.props.cashierId;
  }
  get cashierName(): string {
    return this.props.cashierName;
  }
  get items(): readonly SaleItem[] {
    return this.props.items;
  }
  get total(): Money {
    return this.props.total;
  }
  get payments(): readonly Payment[] {
    return this.props.payments;
  }
  get status(): SaleStatus {
    return this.props.status;
  }
  get clientTransactionId(): string {
    return this.props.clientTransactionId;
  }
  get soldAt(): Date {
    return this.props.soldAt;
  }

  get isVoided(): boolean {
    return this.props.status === "voided";
  }

  amountPaidBy(method: PaymentMethod): Money {
    return Money.sum(
      this.props.payments
        .filter((payment) => payment.method === method)
        .map((payment) => payment.amount),
    );
  }

  get paymentSummary(): PaymentMethod | "split" {
    const methods = new Set(this.props.payments.map((p) => p.method));
    if (methods.size > 1) return "split";
    return this.props.payments[0]?.method ?? "cash";
  }

  get unitCount(): number {
    return this.props.items.reduce(
      (total, item) => total + item.quantity.toNumber(),
      0,
    );
  }

  /**
   * Profit for this sale, or null when any line lacks a recorded cost.
   *
   * All-or-nothing on purpose. A partial figure presented as "profit" is worse
   * than no figure, because it looks authoritative and is not.
   */
  get profit(): Money | null {
    const lineProfits = this.props.items.map((item) => item.lineProfit);
    if (lineProfits.some((profit) => profit === null)) return null;
    return Money.sum(lineProfits as Money[]);
  }

  static totalUnits(quantities: readonly Quantity[]): number {
    return quantities.reduce((total, q) => total + q.toNumber(), 0);
  }
}
