-- =============================================================================
-- AM Express Trading — sales, sale items and payments
-- =============================================================================
--
-- A sale is written once and never edited. Correcting one means voiding it,
-- which restores stock and leaves both records in the history.
--
-- Line items copy the SKU, name, price and cost as they were at the moment of
-- sale. A receipt reprinted next year must show what was actually sold at the
-- price it was actually sold for, even if the product has since been renamed,
-- repriced, or removed from the catalogue.
--
-- Like stock, these tables have no INSERT policy. Sales are written only by
-- public.complete_sale(), which does the whole transaction atomically.
-- =============================================================================

create sequence public.receipt_number_seq as bigint start with 1;

comment on sequence public.receipt_number_seq is
  'Feeds the human-facing receipt number. Gaps are possible after a rolled-back transaction; that is acceptable, duplicates are not.';

-- -----------------------------------------------------------------------------
-- sales
-- -----------------------------------------------------------------------------
create table public.sales (
  id                    uuid primary key default gen_random_uuid(),
  receipt_number        text not null unique,

  cashier_id            uuid not null references public.profiles (id),
  total                 numeric(14, 2) not null check (total > 0),

  status                text not null default 'completed' check (status in ('completed', 'voided')),

  -- Idempotency key generated by the client before its first attempt. If the
  -- connection drops after the database committed but before the response got
  -- home, the retry carries the same key and returns the original sale instead
  -- of selling the stock twice. This unique index is what makes that true.
  client_transaction_id text not null unique,

  sold_at               timestamptz not null default now(),

  voided_at             timestamptz,
  voided_by             uuid references public.profiles (id),
  void_reason           text,

  constraint void_fields_consistent check (
    (status = 'completed' and voided_at is null and voided_by is null and void_reason is null) or
    (status = 'voided'    and voided_at is not null and voided_by is not null and length(btrim(void_reason)) > 0)
  )
);

create index sales_sold_at_idx on public.sales (sold_at desc);
create index sales_cashier_idx on public.sales (cashier_id, sold_at desc);
create index sales_status_idx on public.sales (status) where status = 'completed';

-- -----------------------------------------------------------------------------
-- sale_items
-- -----------------------------------------------------------------------------
create table public.sale_items (
  id          uuid primary key default gen_random_uuid(),
  sale_id     uuid not null references public.sales (id) on delete cascade,

  -- Restricted, not cascaded: a product that has ever been sold cannot be
  -- deleted out from under its own sales history. Retire it instead.
  product_id  uuid not null references public.products (id) on delete restrict,

  sku         text not null,
  name        text not null,
  unit_price  numeric(14, 2) not null check (unit_price >= 0),
  unit_cost   numeric(14, 2) check (unit_cost >= 0),
  quantity    integer not null check (quantity > 0),
  line_total  numeric(14, 2) not null check (line_total >= 0),

  -- Arithmetic the database refuses to get wrong.
  constraint line_total_matches check (line_total = unit_price * quantity),
  -- One line per product per sale, so a stock check on one line cannot pass
  -- while the pair of them exceeds what is on hand.
  constraint one_line_per_product unique (sale_id, product_id)
);

create index sale_items_sale_idx on public.sale_items (sale_id);
create index sale_items_product_idx on public.sale_items (product_id);

-- -----------------------------------------------------------------------------
-- payments
-- -----------------------------------------------------------------------------
create table public.payments (
  id          uuid primary key default gen_random_uuid(),
  sale_id     uuid not null references public.sales (id) on delete cascade,

  method      text not null check (method in ('cash', 'mobile_money')),
  amount      numeric(14, 2) not null check (amount > 0),

  -- Mobile Money is recorded manually — there is no gateway. The reference is
  -- how a payment gets reconciled against the till later, so it is required.
  reference   text,

  recorded_at timestamptz not null default now(),

  constraint mobile_money_needs_reference check (
    method <> 'mobile_money' or length(btrim(coalesce(reference, ''))) > 0
  ),
  -- One amount per method: a split is one cash line and one Mobile Money line.
  constraint one_payment_per_method unique (sale_id, method)
);

create index payments_sale_idx on public.payments (sale_id);
create index payments_method_idx on public.payments (method);

-- Link the stock ledger back to the sale that caused the movement, now that
-- `sales` exists.
alter table public.inventory_movements
  add constraint inventory_movements_sale_fk
  foreign key (sale_id) references public.sales (id) on delete set null;

-- -----------------------------------------------------------------------------
-- Row Level Security
-- -----------------------------------------------------------------------------
alter table public.sales      enable row level security;
alter table public.sale_items enable row level security;
alter table public.payments   enable row level security;

-- A cashier sees their own sales — enough to reprint a receipt they just gave
-- someone. An admin sees the business.
create policy sales_select_own_or_admin
  on public.sales for select to authenticated
  using (
    public.is_admin()
    or (public.is_active_staff() and cashier_id = (select auth.uid()))
  );

create policy sale_items_follow_sale
  on public.sale_items for select to authenticated
  using (
    exists (
      select 1 from public.sales s
      where s.id = sale_items.sale_id
        and (public.is_admin() or s.cashier_id = (select auth.uid()))
    )
    and public.is_active_staff()
  );

create policy payments_follow_sale
  on public.payments for select to authenticated
  using (
    exists (
      select 1 from public.sales s
      where s.id = payments.sale_id
        and (public.is_admin() or s.cashier_id = (select auth.uid()))
    )
    and public.is_active_staff()
  );

-- No INSERT, UPDATE or DELETE policies. Sales are created by
-- public.complete_sale() and voided by public.void_sale(), both SECURITY
-- DEFINER. A client that tries to insert a sale row directly — with, say, a
-- total of one pesewa — is refused by RLS before the request reaches a
-- constraint.
